global:
  version: "1.0.0"

frontend:
  replicaCount: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"

backend:
  replicaCount: 5
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  hpa:
    minReplicas: 3
    maxReplicas: 6

ingress:
  host: prod.127.0.0.1.sslip.io

postgresql:
  primary:
    persistence:
      size: 5Gi # BD más grande en prod

