global:
  version: "1.1.0"

frontend:
  replicaCount: 1
  resources:
    requests:
      cpu: "25m"
      memory: "64Mi"

backend:
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      memory: "256Mi"
  hpa:
    minReplicas: 1
    maxReplicas: 3

ingress:
  host: dev.127.0.0.1.sslip.io

postgresql:
  primary:
    persistence:
      size: 1Gi # BD pequeña en dev
