# charts/backend/templates/secret.yaml — para el backend
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app.kubernetes.io/name: backend-secret
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.global.db.username | quote }}
  DB_PASSWORD: {{ .Values.global.db.password | quote }}